resource "local_file" "generated_files" {
  for_each = local.files

  filename = "${each.value.env}/file${each.value.num}.txt"

  content = "This is file number ${each.value.num} for ${each.value.env} env generated by terraform, The user inputed text is: ${var.user_texts[each.value.env]}"
}
