terraform {
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "local" {}

resource "local_file" "qa_file1" {
  filename = "QA/file1.txt"
  content  = "This is file number 1 <increment here> for QA env generated by terraform, The user inputed text is : < DO NOT HARDCODE, this TEXT can be anything, different for each file and env>"
}
